name: 'build-win'

on:
  push:

jobs:
  
  msys2-windows-2022:

    runs-on: windows-2022

    defaults:
      run:
        shell: msys2 {0}
        #shell: C:\msys64\msys2_shell.cmd -mingw64 -defterm -here -no-start {0}

    steps:

    - name: Cancel previous
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout repo
      uses: actions/checkout@v4.1.1
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        path-type: minimal
        update: true
        release: false
        install: >-
          base-devel
          git
          wget
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-tcl
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-swig
          mingw-w64-x86_64-python

    - name: Show shell configuration
      run: |
        which git && git --version || true
        which cmake && cmake --version || true
        which make && make --version || true
        which python && python --version || true
        which ninja && ninja --version || true
        which tclsh && echo 'puts [info patchlevel];exit 0' | tclsh || true

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Print Repo HEAD
      run: |
        echo && echo "git last log" && git log -1

    # https://sourceforge.net/p/mingw/mailman/message/5690922/
    # https://github.com/capnproto/capnproto/issues/1458
    - name: Build
      run: |
        
        printf "\n\n >>>7zip setup <<<\n"
        export SEVENZIP_BASE_DIR_PATH=${PWD}/7zip
        mkdir -p ${SEVENZIP_BASE_DIR_PATH}
        export SEVENZIP_DIR_PATH=${SEVENZIP_BASE_DIR_PATH}/7z2201-x64
        export SEVENZIP_FILE_PATH=${SEVENZIP_DIR_PATH}/7z.exe
        export SEVENZIP_SFX_FILE_PATH_WIN=$(cygpath -w "${SEVENZIP_DIR_PATH}/7z.sfx" | sed 's/\\/\\\\/g')
        wget --quiet https://www.7-zip.org/a/7zr.exe --directory-prefix=${SEVENZIP_BASE_DIR_PATH}
        wget --quiet https://www.7-zip.org/a/7z2201-x64.exe --directory-prefix=${SEVENZIP_BASE_DIR_PATH}
        cd ${SEVENZIP_BASE_DIR_PATH}
        ${SEVENZIP_BASE_DIR_PATH}/7zr.exe x ${SEVENZIP_BASE_DIR_PATH}/7z2201-x64.exe -y > /dev/null
        ls
        ls ${SEVENZIP_DIR_PATH}
        cd -
        

    - name: Upload OpenFPGA binaries
      uses: actions/upload-artifact@v4.3.0
      if: ${{ success() }}
      with:
        name: openfpga_build
        retention-days: 3
        path: |
          openfpga.7z
          openfpga.sfx.exe
